### ISSUE TITLE
연락할 방법을 몰라서 ㅎㅎㅎㅎ..

### ISSUE THREAD

**Issue by KimHunJin** [redtree0/ArtikWebApp#1]
천규님 혹시 귀국일이 19일인가요? 26일인가요?

**Comment by redtree0** [comment]
아 답답했는데... 다행이네요. 귀국일은 19일 인데, 21일부터 23일까지 Net챌린지 공모전 해커톤 일정이에요...

**Comment by KimHunJin** [comment]
ㅋㅋㅋㅋㅋ 진짜 개발자라서 다행?이네요 ㅋㅋㅋㅋ
저희 27일까지 발표자료 제출 마감이라 한 번은 모여야 할거 같아요

**Comment by redtree0** [comment]
24일부터 27일까지 일정 만들어야죠 ...
